### ISSUE TITLE
Transferring Image to Pc

### ISSUE THREAD

**Issue by sharad386** [brianrho/FPM#10]
Hi,
with the help of your library i am able to enroll, and get template but when i try to use "image to pc code"
it gives me following output
OUTPUT:

Waiting for a finger...
.
.
.
.
.
.
.
.
.
.
Image taken
Starting image stream...

and after this the execution stops ..can you help me out here i want to display the thump impression in my java application . Thank You

**Comment by brianrho** [comment]
Did you wait for it to finish streaming the image? How long did you wait?

**Comment by sharad386** [comment]
Almost 5-10 minutes. is this because my fingerprint sensor is different (the one will all red wires) and my template size is 768 bytes i have seen other fingerprint sensor that generates template of 512 byte!

**Comment by sharad386** [comment]
![screenshot from 2018-10-12 10-38-22](https://user-images.githubusercontent.com/36655100/46849142-9c79f300-ce0b-11e8-8408-0acb78538f5a.png)

**Comment by sharad386** [comment]
after 2-3 seconds 

![screenshot from 2018-10-12 10-38-32](https://user-images.githubusercontent.com/36655100/46849172-c4695680-ce0b-11e8-982f-90d0772fc662.png)

**Comment by sharad386** [comment]
> after 2-3 seconds
> 
> ![screenshot from 2018-10-12 10-38-32](https://user-images.githubusercontent.com/36655100/46849172-c4695680-ce0b-11e8-982f-90d0772fc662.png)

and i get this error
![screenshot from 2018-10-12 10-57-28](https://user-images.githubusercontent.com/36655100/46849577-b9afc100-ce0d-11e8-996a-550681210c40.png)

**Comment by brianrho** [comment]
I don't see any error and it looks like you're using the serial monitor to receive the image. You're supposed to run the python script simultaneously, else how will the image get decoded and saved to your PC? Upload the sketch and then run the script and follow the instructions. Let me know your results.

**Comment by brianrho** [comment]
Took a look again and just spotted the error you spoke of, at the very end of the packet. Would like to see the rest of the error message. Does this happen every time you try the example? Even with the python script?
