### ISSUE TITLE
R551 Did not find fingerprint sensor :(

### ISSUE THREAD

**Issue by MaazSk** [brianrho/FPM#13]
Hie,
I have purchased a R551 sensor it was working nice when I uploaded some of the codes and was able to save the fingerprints and access those templates, but all of the sudden it stopped working and I am getting the message "Did not find fingerprint sensor :(" on the serial monitor.
If anyone knows how to solve the issue please help me out.
Thanks in advance

**Comment by brianrho** [comment]
Did you run the set_parameters example? If you did, it may have changed your baud rate to 9600. So change your SoftSerial baud rate in the enroll example and try again

**Comment by MaazSk** [comment]
I tried changing the baud rate also but I am getting the same message "Did not find fingerprint sensor". I have one more sensor it is working good on the same piece of code does this mean my sensor is broke or is having some problems and it will not work if yes can you suggest me how to fix it @brianrho 
Thank You!

**Comment by mohammadhasanzadeh** [comment]
Unfortunately, I have the same problem on R308 fingerprint sensor, but the same code works on ZFM-60!
Also, I tried to change baud rate to `9600`, but problem not fixed.

**Comment by MaazSk** [comment]
The problem is solved actually I had uploaded the change password code which changed the password to "0x12345678", now I have changed the password again to "0" and the sensor is working fine 
Thank You! for your help @brianrho

**Comment by brianrho** [comment]
Ah, glad to hear it worked out, will have to add a warning to the sketch.
