### ISSUE TITLE
Uploading image to R305

### ISSUE THREAD

**Issue by amarpreetsingha** [brianrho/FPM#2]
Hii brianrho. Can you help me in uploading an image file to R305 using arduino. As i dont want to enroll by scanning through FPS. R305 datasheet contains DownImage command description so just needed help in implementing that functionality.

**Comment by amarpreetsingha** [comment]
Correction : downloadFP function definition is in datasheet not in adafruit lib.

**Comment by brianrho** [comment]
Currently busy with other stuff. Will add that when I can.

**Comment by sand007man** [comment]
> Hii brianrho. Can you help me in uploading an image file to R305 using arduino. As i dont want to enroll by scanning through FPS. R305 datasheet contains DownImage command description so just needed help in implementing that functionality.

hey were you able to implement that functionality using Arduino?? even I am stuck in that part??
