### ISSUE TITLE
Best sensor to use?

### ISSUE THREAD

**Issue by nilsmelchert** [brianrho/FPM#29]
Hi,
At first, thank you for providing this code. I have a couple of questions regarding this library.

- Is there a sensor which worked best in the past? 

- Is it also possible to use capacitive sensors?

- Did I get that right from the documentation, that I am also able to read out the "raw" fingerprint from the sensor to the computer?

Thanks a lot for your answers

**Comment by nilsmelchert** [comment]
Sorry. I should have read more before asking questions. ;-)

**Comment by brianrho** [comment]
Glad you found it useful :-)
As for reliable sensors, most of them out there are decent, the only limitation they have individually is their supported features and I've recommended a few in the README that offer most things people need. But you can verify with their datasheets to be sure they support the features you want.
