### ISSUE TITLE
Upload Image To Reader Slot

### ISSUE THREAD

**Issue by imamminer** [brianrho/FPM#31]
Hi.
Nice library, thanks.
image to pc works! 
Please advise on how to go about uploading from the pc back to the reader slot.

Regards

**Comment by brianrho** [comment]
I never got around to adding this functionality. Think I'll look into it maybe in a few days

**Comment by brianrho** [comment]
> how to go about uploading from the pc back to the reader slot.

Took a few years but finally added an example for doing this, as part of the `templates` example (`writeTemplate()`).
