### ISSUE TITLE
Template file download time

### ISSUE THREAD

**Issue by abhibhatia98** [brianrho/FPM#40]
Hi @brianrho  

Could you please let me know how much time does it take to download the template file from sensor to host PC?

It will be very helpful to me.

**Comment by brianrho** [comment]
At the default 57600 baud for the sensor and 9600 baud for Serial, I believe it takes maybe 2s, and most of that is probably spent on just printing the data, I haven't really measured any of this. You can do that yourself easily if you have a sensor already.
