### ISSUE TITLE
Unable to save image using c language

### ISSUE THREAD

**Issue by kumar-ashish1** [brianrho/FPM#43]
Hi i am getting some problem while trying to save image using c getting problem in writing header , color platte and image buffer to file in c lanuage. Pls help

**Comment by brianrho** [comment]
I'm afraid I can't help you with your own code. You'll have to go study the existing Python script and then think/do some research on porting it to C. If you have any more _precise_ questions about the script itself, I may be able to answer.

**Comment by kumar-ashish1** [comment]
Hi i have done lots of r&d and finally got success with a little bit problem.In python i am getting bright image as compare to clanguage  . I know its due to color palatte so can u help me pls.
![python](https://user-images.githubusercontent.com/55408004/161054052-c3b11124-53c5-4cde-96f0-04bbeeff352a.png)
![clang](https://user-images.githubusercontent.com/55408004/161054059-7c69232d-054a-46db-b3f9-9f1ac1e4da3a.png)

**Comment by kumar-ashish1** [comment]
Ok thanks . After doing lots of r&d finally i have completed my code. Thank-you so much .

**Comment by brianrho** [comment]
Glad to hear it, good luck!
