### ISSUE TITLE
Showing error : Communication Error

### ISSUE THREAD

**Issue by Repulsar19** [brianrho/FPM#50]
Hello, I'm using a HLK-FPM383F Fingerprint sensor for my project. I'm usning your code for enrolling and deleting the fingerprints images. All my connections are right and also fingerprint sensor is detected as well. But when I enter a slot number, it starts to show 'Communication Error' . What am I missing ? I have uploaded ' Enroll with LED Control' program

**Comment by brianrho** [comment]
Hi, if you still have the problem, can you try git-pulling and re-testing with the latest source? 

If the problem still happens:
-  change the value of `FPM_LOG_LEVEL` on this line to `FPM_LOG_LEVEL_V_VERBOSE`:
https://github.com/brianrho/FPM/blob/7ecf3489bbc56d8d22988100074eac60953983c8/src/fpm_logging.h#L24
- re-upload and redo the test with the Serial monitor open
- paste the entire contents of the Serial Monitor after the failure happens.

**Comment by brianrho** [comment]
Closing this. You can re-open when you have the requested data, if you still have the problem.

**Comment by Repulsar19** [comment]
Hello, thank you for your reply. Sorry I was not active so can't able to thank you earlier. Will test it and update you about it :)
