### ISSUE TITLE
LED Control for ZW111 Fingerprint sensor

### ISSUE THREAD

**Issue by Repulsar19** [brianrho/FPM#54]
Hello, I have tried using your library and Im using ZW111 Fingerprint sensor. Though the code is working fine, i cant able to control LED for it. :(

**Comment by brianrho** [comment]
Hi. As explained in `fpm.h`, only a few sensors are known to allow LED control:

```
    /* these 3 have been tested successfully only on ZFM60 so far. 
       May yet work on other/newer sensors */
    FPMStatus ledOn(void);
    FPMStatus ledOff(void);
    FPMStatus getImageOnly(void);
```

I cannot find your sensor's datasheet, so unless you have some evidence that it supports such control as well as a description of the necessary commands, then it's best to assume it doesn't have that support.

**Comment by Repulsar19** [comment]
hello sir sorry for late reply, i have got a datasheet of same fingerprint module (zw111), with commands list can you help me in this? should i send it to you here?

**Comment by brianrho** [comment]
Sure, you can attach the PDF here.
