### ISSUE TITLE
Touch

### ISSUE THREAD

**Issue by beryindo** [brianrho/FPM#7]
How to Use Touch PIN?

**Comment by brianrho** [comment]
What touch pin?

**Comment by edautz** [comment]
> How to Use Touch PIN?

https://github.com/brianrho/FPM/issues/4#issuecomment-467225878

**Comment by devegied** [comment]
FPM10A Fingerprint Reader Sensor Module from AliExpress have two more pins: T-OUT and T-3V3. These are for integrated touch sensor.
I done some RE on part of sensor: ![Schematic](https://user-images.githubusercontent.com/24810903/84484521-8c32af00-aca3-11ea-8009-7f5a39211455.png)
The 233DH TonTouch IC is used for touch sensor and with this configuration (TOG - low, AHLB - high) on output T-OUT we should get HIGH when there is nothing on fingerprint sensor and HIGH when finger is on the sensor.
